import type { Metadata } from 'next';
import '../styles/globals.css';
import { Provider } from "react-redux";
import store from "@/redux/store";
import { ProviderRedux } from "@/components/Layout/ProviderRedux";

export const metadata: Metadata = {
  title: 'Trac nghiem online',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProviderRedux>
          <div>{children}</div>
        </ProviderRedux>
      </body>
    </html>
  );
}
