import type { Metadata } from "next";
import "../styles/globals.css";
import MainLayout from "@/components/Layout/MainLayout";

export const metadata: Metadata = {
  title: "Trac nghiem online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body><MainLayout>{children}</MainLayout></body>
    </html>
  );
}
